version: '3.9'

services:

    nginx-proxy:
        container_name: nginx-proxy
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - certs:/etc/nginx/certs
            - vhost.d:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro
        restart: unless-stopped

    letsencrypt:
        container_name: letsencrypt
        image: jrcs/letsencrypt-nginx-proxy-companion
        volumes_from:
            - nginx-proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
    default:
        name: nginx-proxy
        external: true

volumes:
    certs:
        name: nginx-proxy___etc_nginx_certs
    vhost.d:
        name: nginx-proxy___etc_nginx_vhost.d
    html:
        name: nginx-proxy___usr_share_nginx_html
