version: '3.9'

services:

    jenkins:
        container_name: jenkins
        image: jenkins/jenkins
        # ports:
        #     - "8000:8080"
        # environment:
        #     VIRTUAL_HOST: jenkins.domain.com
        #     VIRTUAL_PORT: 8000
        volumes:
            - jenkins_home:/var/jenkins
        restart: unless-stopped

networks:
    default:
        name: nginx-proxy
        external: true

volumes:
    jenkins_home:
        name: jenkins-var_jenkins
