version: '3.9'

services:

    jenkins:
        container_name: jenkins
        image: jenkins/jenkins
        environment:
            # LETSENCRYPT_HOST: jenkins.domain.com
            # VIRTUAL_HOST: jenkins.domain.com
            VIRTUAL_PORT: 8080
        volumes:
            - /var/jenkins_home
        restart: unless-stopped

networks:
    default:
        name: nginx-proxy
        external: true
